### ISSUE TITLE
AUTOINCREMENT on PRIMARY KEY fails to create table

### ISSUE THREAD

**Issue by loki666** [foxykeep/ContentProviderCodeGenerator#11]
should be 
_id id_type PRIMARY KEY AUTOINCREMENT, ...

**Comment by frapontillo** [comment]
I have this issue as well, the `AUTOINCREMENT` only works when it is declared next to a `PRIMARY KEY` definition, and it won't work in a [table constraint](http://www.sqlite.org/syntaxdiagrams.html#table-constraint) definition.
The `ContentProviderCodeGenerator` should declare a primary key next to the column definition if the same column has to be automatically incremented:

`CREATE TABLE tableName (_id integer PRIMARY KEY AUTOINCREMENT, desc text);`

and not:

~~`CREATE TABLE tableName (_id integer AUTOINCREMENT, desc text, PRIMARY KEY (myPK));`~~

Also, the AUTOINCREMENT definition needs to be added to the [`upgradeTable` method](https://github.com/foxykeep/ContentProviderCodeGenerator/blob/master/generator/res/content_subclass_upgrade.txt#L3).

**Comment by foxykeep** [comment]
Ok so that the issue is that AUTOINCREMENT and multi columns PRIMARY KEY cannot be used together. 
And as you said there is a special syntax for PRIMARY KEY AUTOINCREMENT.

Also AUTOINCREMENT is only working with a PRIMARY KEY field.

So adding more constraint to the generator logic to manage these cases. Fix incoming.
